config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'

  root 'pages#one'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-inverse bg-light">

      <div class="collapse navbar-collapse" id="navbar_pro">
       
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= pages_one_path %>">One</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= pages_two_path %>">Two</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= pages_three_path %>">Three</a>
          </li>
        </ul>

      </div>
    </nav>

      <%= yield %>
      
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Rodrigo Andres Osorio Barra</h1>

app/views/pages/three.html.erb
<h1> Page Three </h1>

<p>Lorem ipsum dolor sit amet consectetur adipiscing, elit malesuada risus tempor nascetur accumsan, taciti quis at potenti urna. Ante bibendum vestibulum sapien mi sodales cras per, maecenas himenaeos lacinia faucibus nisi aptent, hac nunc accumsan enim fusce imperdiet. Quisque ultrices nam feugiat conubia class aenean ac ad imperdiet per vulputate urna, porta accumsan suscipit sociosqu nascetur magnis sagittis leo interdum netus laoreet.</p>

app/views/pages/two.html.erb
<h1>Pages two</h1>

<%= image_tag 'routes.png' %>